### ISSUE TITLE
Handling voltage measurements

### ISSUE THREAD

**Issue by MartaVanin** [Electa-Git/PowerModelsDistributionStateEstimation.jl#13]
These are currently three-phase even though users are single-phase. This is not realistic.
While we wait for PMD v0.10.0 to only explicitly define conductors, do we keep this hack or propose a more realistic work around?
A possible solution would be to give only a measurement on the user's phase and set the other two voltages equal to the voltage on the adjacent three-phase main bus. It entails more equality constraints but doesn't look like comp time would go up because of this.

**Comment by timmyfaraday** [comment]
Awaiting PMD v0.10.
