### ISSUE TITLE
Decide on if/how to handle/expand se problem with SDP equations

### ISSUE THREAD

**Issue by MartaVanin** [Electa-Git/PowerModelsDistributionStateEstimation.jl#18]
A basic SDP state estimation is now available.
It is based on the SDPUBFPowerFlow of PMD, where PSD constraints are modelled specifically as conic --> Ipopt can't deal with them. We need either SCS (free, for tests) or mosek/other efficient conic solvers. 
There is no problem with WLAV, but WLS is not conic (is quadratic), so we should decide what to offer:
- We only provide the formulation above and relax the WLS criterion (there is a basic silly relaxation of WLS right now. Might be 
   a research topic to figure out nice relaxations of WLS or other conic criteria)
- We re-write the explicit conic constraints (or see what the implementation status of SDPUBFKCLMXPowerModel in PMD is), so 
   ipopt accepts the SDP formulation and we can plug-in any (non-convex) estimation criterion we like. 
- We provide both the above possibilities

**Comment by timmyfaraday** [comment]
I think we were gonna go all conic on the WLS, right?

**Comment by MartaVanin** [comment]
as a first step yes, but I'd still leave this open for if we want to allow SDP equations + non-conic objectives or constraint.
I won't do it now.. also not sure we necessarily should, but let's give it some more time
