### ISSUE TITLE
Improve computational speed with wls (and non-gaussian?)

### ISSUE THREAD

**Issue by MartaVanin** [Electa-Git/PowerModelsDistributionStateEstimation.jl#19]
just a reminder and a place to put new ideas if they pop-up
- try different rescalers
- try relaxed wls
- try stricter variable bounds
- compare different (exact) formulations to see what's faster
- talk to people (Frederik, ...)

**Comment by timmyfaraday** [comment]
You forgot:
- testing whether the bounds on rho are an issue

**Comment by MartaVanin** [comment]
For computational time?
Because I added a big M and now the logpdf works: it converges to the global minimum, when it converges 😝

**Comment by timmyfaraday** [comment]
Random big M generally results in numerical issues... 
Any quantification on the percentage of cases where it doesn't converge?

**Comment by MartaVanin** [comment]
not yet, it varies with different pf formulations, too. I made the big M settable in the settings dictionary, so it's easier to play with
