### ISSUE TITLE
Errors when running tests internally

### ISSUE THREAD

**Issue by timmyfaraday** [Electa-Git/PowerModelsDistributionStateEstimation.jl#27]
When running the tests internally, many tests fail due to 

`SystemError: opening file "/Users/tvanacke/.julia/packages/PowerModelsDistributionStateEstimation/QCTn0/test/data/enwl/measurements/temp.csv": Permission denied`

**Comment by MartaVanin** [comment]
This is annoying, we can't make sure that directory has write access for each user.
I see two possible solutions:
1) We either save and store a measurement CSV for each test, or 
2) we create a temporary directory with write access with "cd(mktempdir())". I would suspect this might also create issues, but it actually seemed to work here: https://github.com/JuliaLang/julia/issues/17829

I will try the second one tomorrow or so

**Comment by MartaVanin** [comment]
I merged to master my branch with the 2. solution, testing works locally for me, but it was also the case before, so would be great if you could check whenever you have a minute

**Comment by MartaVanin** [comment]
closed by #28
