### ISSUE TITLE
PMDSE downgrading other packages

### ISSUE THREAD

**Issue by gaadis** [Electa-Git/PowerModelsDistributionStateEstimation.jl#50]
When I install the PowerModelsDistributionStateEstimation package, it downgrades the version of most of the other packages that I have installed making it impossible for pre-compilation.  I am running Julia 1.8.5 in Visual Studio Code 1.77.2

Below is the status of my environment showing the packages with their respective versions prior to installing PMDSE
![image](https://user-images.githubusercontent.com/37007341/231806309-2df9bf86-c0fa-4ab3-9549-46e353a6e8f7.png)

After installing the PMDSE package, the status of my environment is shown below. I tried running my code after installing the PMDSE package and Ipopt won't compile as I need Ipopt 0.9 or higher but PMDSE downgrades Ipopt to version 0.7
![image](https://user-images.githubusercontent.com/37007341/231812119-f297b301-f250-436f-8c62-72d748b3f4e8.png)
![image](https://user-images.githubusercontent.com/37007341/231812335-c15d7db9-a11a-462c-871f-3889953759ac.png)

Status
![image](https://user-images.githubusercontent.com/37007341/231812525-c1843518-728e-481f-bc2f-27fa9165f390.png)

status --outdated
![image](https://user-images.githubusercontent.com/37007341/231815696-976e11b5-4143-4832-8729-ce0b0694135d.png)

Can you please update PMDSE or is there any other way around this issue.

**Comment by gaadis** [comment]
Okay. I'll see what I can do while I wait for your upgrade. Thanks for your timely response.

**Comment by gaadis** [comment]
Checking in to see if the upgrade is done. Thanks.

**Comment by gaadis** [comment]
> I am planning an ecosystem upgrade in the next weeks because indeed, the package is lagging a bit behind. But it is going to take a while before I get to it. What you can see on your side is if
> 
> 1. see if you can remove some packages from your environment or if some lower versions would still work for your purposes. For instance, are you sure you can't use Ipopt 0.7 instead of 0.9?
> 2. as PMDSE takes CSV files as input data, you could "decouple " the stages of your implementation, if that is possible. Although it is not very handy.

 Checking in to see if the upgrade has been done. Thanks.

**Comment by MartaVanin** [comment]
@gaadis you can check the progress on the update in this PR: https://github.com/Electa-Git/PowerModelsDistributionStateEstimation.jl/pull/51 

some work has been done, but it's not finished yet..

**Comment by MartaVanin** [comment]
should now be fully fixed by #51 , just upgrade PMDSE to version 0.7.0
